/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoveryPasswordRouteImport } from './routes/recovery-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected.index'
import { Route as ProtectedNotificationsIndexRouteImport } from './routes/_protected.notifications.index'
import { Route as ProtectedEventsIndexRouteImport } from './routes/_protected.events.index'
import { Route as ProtectedEventsEventIdRouteImport } from './routes/_protected.events.$eventId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryPasswordRoute = RecoveryPasswordRouteImport.update({
  id: '/recovery-password',
  path: '/recovery-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsIndexRoute =
  ProtectedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedEventsIndexRoute = ProtectedEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEventsEventIdRoute = ProtectedEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/check-email': typeof CheckEmailRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/login': typeof LoginRoute
  '/recovery-password': typeof RecoveryPasswordRoute
  '/register': typeof RegisterRoute
  '/events/$eventId': typeof ProtectedEventsEventIdRoute
  '/events/': typeof ProtectedEventsIndexRoute
  '/notifications/': typeof ProtectedNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/check-email': typeof CheckEmailRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/login': typeof LoginRoute
  '/recovery-password': typeof RecoveryPasswordRoute
  '/register': typeof RegisterRoute
  '/': typeof ProtectedIndexRoute
  '/events/$eventId': typeof ProtectedEventsEventIdRoute
  '/events': typeof ProtectedEventsIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/login': typeof LoginRoute
  '/recovery-password': typeof RecoveryPasswordRoute
  '/register': typeof RegisterRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/events/$eventId': typeof ProtectedEventsEventIdRoute
  '/_protected/events/': typeof ProtectedEventsIndexRoute
  '/_protected/notifications/': typeof ProtectedNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/email-verified'
    | '/login'
    | '/recovery-password'
    | '/register'
    | '/events/$eventId'
    | '/events/'
    | '/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/check-email'
    | '/email-verified'
    | '/login'
    | '/recovery-password'
    | '/register'
    | '/'
    | '/events/$eventId'
    | '/events'
    | '/notifications'
  id:
    | '__root__'
    | '/_protected'
    | '/check-email'
    | '/email-verified'
    | '/login'
    | '/recovery-password'
    | '/register'
    | '/_protected/'
    | '/_protected/events/$eventId'
    | '/_protected/events/'
    | '/_protected/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  LoginRoute: typeof LoginRoute
  RecoveryPasswordRoute: typeof RecoveryPasswordRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-password': {
      id: '/recovery-password'
      path: '/recovery-password'
      fullPath: '/recovery-password'
      preLoaderRoute: typeof RecoveryPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications/': {
      id: '/_protected/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof ProtectedNotificationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/events/': {
      id: '/_protected/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof ProtectedEventsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/events/$eventId': {
      id: '/_protected/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof ProtectedEventsEventIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedEventsEventIdRoute: typeof ProtectedEventsEventIdRoute
  ProtectedEventsIndexRoute: typeof ProtectedEventsIndexRoute
  ProtectedNotificationsIndexRoute: typeof ProtectedNotificationsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedEventsEventIdRoute: ProtectedEventsEventIdRoute,
  ProtectedEventsIndexRoute: ProtectedEventsIndexRoute,
  ProtectedNotificationsIndexRoute: ProtectedNotificationsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  EmailVerifiedRoute: EmailVerifiedRoute,
  LoginRoute: LoginRoute,
  RecoveryPasswordRoute: RecoveryPasswordRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
